### ISSUE TITLE
self.USER_AGENT doesn't exist in this class

### ISSUE THREAD

**Issue by logr4y** [ShielderSec/webtech#1]
https://github.com/ShielderSec/webtech/blob/13f56abed8a5ff40f4f01902fdbf5b4add0ac22d/webtech/target.py#L111

**Comment by TheZ3ro** [comment]
Thanks for the issue,

Actually that line was useless and we forgot to remove it.
When `start_from_url` is called, it checks for the schema and if it's equal to `file` it calls `parse_http_file`.
This latter function shouldn't re-call `scrape_url` since we explicitly have a `file://` schema.
Now WebTech returns a `FileNotFoundException` instead of trying to scrape "something".
Good catch!

Fixed in this commit from the **dev** branch:
https://github.com/ShielderSec/webtech/commit/f8e742c2197681b93a76290a395fd1ab9853b95e

Will close the issue when the commit ends up in master branch

**Comment by TheZ3ro** [comment]
Closing since I've merged #3 into master
